apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ .Values.product.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Amohan9676$
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_USER
              value: mohan
            - name: MYSQL_PASSWORD
              value: Amohan9676$
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.product.namespace }}
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
